// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using REST_Practise.Data;

#nullable disable

namespace SOAP_WSDL.Migrations
{
    [DbContext(typeof(ERPContext))]
    [Migration("20230912173013_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SOAP_WSDL.Models.DepartmentModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DepartmentName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f984f49c-3c1f-437e-8c0f-632e57db0283"),
                            DepartmentName = "Engineering"
                        },
                        new
                        {
                            Id = new Guid("407196ae-4e83-423f-adb0-b04f5ef1cfef"),
                            DepartmentName = "Quality Assuarance"
                        },
                        new
                        {
                            Id = new Guid("85ee90c9-fea5-42f4-a937-15e5ffe04e44"),
                            DepartmentName = "Human Resource"
                        },
                        new
                        {
                            Id = new Guid("15b508b6-0b06-4a17-b9fa-c4e7bcc4d780"),
                            DepartmentName = "Support"
                        },
                        new
                        {
                            Id = new Guid("e55e6a1a-80f8-465c-bcec-5aa8aeae5d5b"),
                            DepartmentName = "Managed Services"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
